### ISSUE TITLE
Is it only good at image related problems? 

### ISSUE THREAD

**Issue by xuzhang5788** [StanfordVL/taskonomy#10]

**Comment by amir32002** [comment]
I'm not clear what your question is. Do you have a question about the code base released on github? 

If you're asking a general question and the taskonomy paper, the focus and goal is on perception. The formulation does not have to deal with visual data at all steps and some folks are looking into sister domains, e.g. speech, natural language, etc but that's neither our focus nor our goal here. Reading the paper should help with grasping which components are general and which ones image focused.
