### ISSUE TITLE
Cannot download model

### ISSUE THREAD

**Issue by heiheiya** [StanfordVL/taskonomy#13]
The URL in the download_model.sh is unreachable, where can I download the model?

**Comment by heiheiya** [comment]
Do you mean sh tools/download_model.sh?@emergencyd
I tried it, but failed.

**Comment by amir32002** [comment]
`tools/download_model.sh` was just verified and is working. The issue must be on your side. 

Either way, we made a mirror of the models folder at the following link for those that can't access AWS. The uncompressed content should go in `/taskbank/temp/` 

`http://downloads.cs.stanford.edu/downloads/taskonomy_taskbankv1_models/taskonomy_taskbankv1_models.tar`

**Comment by heiheiya** [comment]
@amir32002 Thank you very much!

**Comment by YanYas** [comment]
It seems that directory names cannot contain spaces. This appeared to remedy the issue for me.
