### ISSUE TITLE
Valid classes for scene categorization

### ISSUE THREAD

**Issue by SimonVandenhende** [StanfordVL/taskonomy#19]
Hi, the supplementary materials of the Taskonomy paper mention that 63 categories from the MIT places dataset were used for training the scene categorization model. 
I expected that the selected categories were contained in the following file './taskonomy/taskbank/lib/data/places_classes_to_keep.txt'
However this file only contains 31 valid classes, marked with a '1'. 
Could you specify which classes you used for training the scene categorization model? 
Thanks in advance.

**Comment by b0ku1** [comment]
Hi Simon,

Please see function `class_places_workspace_and_home` in `load_ops.py` for the list of classes used in training (a numpy binary array). The same binary array is also in `task_viz.py`. Sorry for the confusion.

Best,
Will
