### ISSUE TITLE
How to train my dataset?

### ISSUE THREAD

**Issue by RobotIntelligence** [StanfordVL/taskonomy#2]
This is a nice project, Thanks for your sharing!
I want to train my dataset. 
How to do it?

**Comment by amir32002** [comment]
Can you clarify what you want to train? The entire taskonomy framework or the task bank?

**Comment by RobotIntelligence** [comment]
Recently， I want to study edge detection. How do I train it ?

**Comment by amir32002** [comment]
It seems your question is a general deep learning one is not in direct relevance to taskonomy or transfer learning. I'd suggest you refer to  the deep learning tutorials available on the web.
