### ISSUE TITLE
Euclidean Distance ?

### ISSUE THREAD

**Issue by bareblackfoot** [StanfordVL/taskonomy#22]
How can I do Euclidean distance estimation?
Rgb2depth and rgb2mist both estimate 0~1 depth values.

**Comment by alexsax** [comment]
The README mentions that these map to metric depth in that the images are 16-bit depth and 1 pixel intensity = 1/512m. So a value of 2^16-1 maps to a max range of 128m. Whatever data loader you're using probably maps the 16-bit images from [0, 2^16-1] -> [0,1].
