### ISSUE TITLE
How could I get the entire datasets?

### ISSUE THREAD

**Issue by theFool32** [StanfordVL/taskonomy#3]
I notice that
```
More of code, models, and dataset of Taskonomy coming soon. 
```
in readme have been commented. Does it mean the dataset will not be published?

Thanks a lot.

**Comment by amir32002** [comment]
The dataset and everything else will be published.  We are releasing them as we finishing processing each.

**Comment by emergencyd** [comment]
is that completed? Where can I get the validation and testing dataset?
Thank you

**Comment by amir32002** [comment]
Per the instructions on the website, you should send us an email to receive the service terms and download links of the dataset.  

http://taskonomy.stanford.edu/#data
