### ISSUE TITLE
Access to dataset

### ISSUE THREAD

**Issue by thunderball7cd** [StanfordVL/taskonomy#30]
Hi! I'm so excited of your work and dataset! Actually, I'm a bit confused about how to contact the authors. I was wondering how to get access to the dataset? Sorry, that I'm asking question here, I didn't find instructions [here](http://taskonomy.stanford.edu/#data) as it described in this [issue](https://github.com/StanfordVL/taskonomy/issues/3). Thank you!

**Comment by amir32002** [comment]
As the dataset readme.md and the linked issue above says, we have to receive an email from you to be able to share the data. Please send an email and we'll send you the instructions.
