### ISSUE TITLE
Could you provide direct links of pytorch pretrained models for convience?

### ISSUE THREAD

**Issue by sccbhxc** [StanfordVL/taskonomy#33]
I can not find the download links of pytorch pretrained models from https://github.com/StanfordVL/taskonomy/tree/master/taskbank .
So could you provide direct links of pytorch pretrained models for convience?

**Comment by alexsax** [comment]
The page you linked directs you to [this package](https://github.com/alexsax/midlevel-reps/tree/master#installing-visualpriors) which has detailed instructions for how to download the networks via `pip` and for using the networks. I think that installing via that `visualapriors` package is probably the easiest way to download the models.

However, if you prefer the direct download links, those are available here: [https://github.com/alexsax/visual-prior/tree/networks/assets/pytorch](https://github.com/alexsax/visual-prior/tree/networks/assets/pytorch).
