### ISSUE TITLE
how to train the network on single task

### ISSUE THREAD

**Issue by GuoleiSun** [StanfordVL/taskonomy#35]
Could you provide more details about training?

Prepare dataset, Train for different tasks, and so on

**Comment by alexsax** [comment]
Detailed for how _we_ trained the networks are in the [supplementary material](http://taskonomy.stanford.edu/taskonomy_supp_CVPR2018.pdf). The code is available in this repository as well.

Regarding general-purpose data loaders and such, perhaps I will write a pytorch dataloader and release it here. If you end up writing one, please share it via pull request!

**Comment by GuoleiSun** [comment]
Hi @alexsax, thanks for your reply. 

Currently, I want to train individual tasks and I am looking at your [training code](https://github.com/StanfordVL/taskonomy/tree/master/code). But i easily got lost.

In the readme, you mention that:

To create the taskonomy, we used the following procedure:
    Create all task-specific configs (using tools/scripts/ and saving to experiments/)
    Select which config to run, then train the task-specific network using tools/train.py
    Create all transfer configs (using tools/scripts/ and saving to experiments/)
    Select which config to run, then train the transfer network using tools/transfer.py
    Compute losses with extract_losses.py
    Generate win rates and affinities with one of the methods in analysis/

It is difficult for readers to follow. For example, the first step is to create configs by using ..., how? There are tens of files in tools/scripts/, which one to run and what's the running commands? Please point out if I miss understand something. Thanks
