### ISSUE TITLE
About the Camera Parameters

### ISSUE THREAD

**Issue by JennyGao00** [StanfordVL/taskonomy#43]
Recently, I'm intend to use your datasets to train my model, but I need to know the exact number of #Camera Parameters#, so, I want to ask that how you set it in your experiment?
Looking forward to your reply.

**Comment by louzq16** [comment]
> Recently, I'm intend to use your datasets to train my model, but I need to know the exact number of #Camera Parameters#, so, I want to ask that how you set it in your experiment? Looking forward to your reply.

hello, have you solved the problem of parsing #Camera Parameters# of taskonomy dataset?

**Comment by MingshuaiZhao** [comment]
hi,  @JennyGao00 ,Can you tell me where you found the parameters of the camera？
Thanks!
