### ISSUE TITLE
"tarfile.ReadError: unexpected end of data" when downloading rgb_large_woodbine.tar

### ISSUE THREAD

**Issue by taromakino** [StanfordVL/taskonomy#50]
I get "tarfile.ReadError: unexpected end of data" when downloading the "tiny" version of the dataset. This appears to be the only file that fails to finish downloading.

**Comment by alexsax** [comment]
Thanks for pointing this out--the RGB large file for woodbine appears corrupted. I've excluded the whole building from the downloader. If there are any other problems please do reopen this issue.

**Comment by alexsax** [comment]
P.s. you'll need to update with `pip install --upgrade 'omnidata-tools'`
