### ISSUE TITLE
How to download specific subfolders? e.g. only rgb, class_object, class_scene

### ISSUE THREAD

**Issue by taromakino** [StanfordVL/taskonomy#51]
Is there a way to restrict the download to specific subfolders, for example since I'm only interested in object classification and scene classification, I'd prefer to only download rgb, class_object, and class_scene.

**Comment by alexsax** [comment]
`omnitools.download rgb class_object class_scene --components taskonomy --subset fullplus`

**Comment by eyildiz-ugoe** [comment]
> `omnitools.download rgb class_object class_scene --components taskonomy --subset fullplus`

this redownloads what's already downloaded. any tag to tell it to skip what's already in place? how can we know if we have these specific folders complete? like is there a command that checks if rgb is complete? it  just goes on and on forever.
